export const MOCK_ADDRESSES = [
  {
    line1: "H-12, Green Park, Block A",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110016",
  },
  {
    line1: "Flat 503, Lajpat Nagar Phase II",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110024",
  },
  {
    line1: "Plot 21, Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201309",
  },
  {
    line1: "H-88, Gomti Nagar Extension",
    city: "Lucknow",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "226010",
  },
  {
    line1: "Flat 302, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400069",
  },
  {
    line1: "C-404, Powai Lake View",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400076",
  },
  {
    line1: "Row House 9, Baner Road",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411045",
  },
  {
    line1: "Flat 12B, Viman Nagar",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411014",
  },
  {
    line1: "No. 45, Whitefield Main Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560066",
  },
  {
    line1: "Flat 701, BTM Layout 2nd Stage",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560076",
  },

  // ---- repeat pattern safely across states ----

  {
    line1: "Plot 16, Anna Nagar West",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600040",
  },
  {
    line1: "Flat 209, Velachery Main Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600042",
  },
  {
    line1: "House No 88, Salt Lake Sector V",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700091",
  },
  {
    line1: "Flat 5A, Ballygunge Place",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700019",
  },
  {
    line1: "Villa 17, Banjara Hills Road No 12",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500034",
  },
  {
    line1: "Flat 404, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500032",
  },
  {
    line1: "House 21, Sector 15",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160015",
  },
  {
    line1: "Flat 601, HSR Layout Sector 2",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560102",
  },
  {
    line1: "Plot 33, Rajarhat New Town",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700135",
  },
  {
    line1: "Flat 402, Indiranagar 100 Ft Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560038",
  },

  {
    line1: "Flat 402, Shanti Heights, J.P. Road",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400053",
  },
  {
    line1: "Plot No. 45, Sector 12-A, Vashi",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400703",
  },
  {
    line1: "12/B, Sterling Apartment, Pedder Road",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400026",
  },
  {
    line1: "Villa 7, Palm Grove, ECR Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600041",
  },
  {
    line1: "No. 88, 4th Main, Malleshwaram",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560003",
  },
  {
    line1: "H.No 4-12, Banjara Hills, Road No. 10",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500034",
  },
  {
    line1: "7th Floor, DLF Cyber City, Phase III",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122002",
  },
  {
    line1: "B-404, Maple Leaf, Powai",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400076",
  },
  {
    line1: "C-21, Hauz Khas Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110016",
  },
  {
    line1: "Flat 101, Orchid Residency, Somajiguda",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500082",
  },
  {
    line1: "House No. 56, Sector 15-C",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160015",
  },
  {
    line1: "A/P-90, Kalyani Nagar",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411006",
  },
  {
    line1: "33, Salt Lake City, Sector II",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700091",
  },
  {
    line1: "45, Gariahat Road, Ballygunge",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700019",
  },
  {
    line1: "Flat 2C, Emerald Isle, Koramangala 4th Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560034",
  },
  {
    line1: "H-15, Chittaranjan Park",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110019",
  },
  {
    line1: "B-2, Gomti Nagar, Near Riverview",
    city: "Lucknow",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "226010",
  },
  {
    line1: "No. 121, Anna Salai",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600002",
  },
  {
    line1: "Plot 44, Jubilee Hills, Check Post",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500033",
  },
  {
    line1: "201, Sunrise Apartments, Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560066",
  },
  {
    line1: "Shop 12, MG Road, Camp",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411001",
  },
  {
    line1: "E-9, Malviya Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "302017",
  },
  {
    line1: "Flat 505, Galaxy Towers, Kondapur",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500084",
  },
  {
    line1: "Villa 102, Prestige Lakeside Habitat",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560087",
  },
  {
    line1: "G-4, Lajpat Nagar III",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110024",
  },
  {
    line1: "22, Alipore Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700027",
  },
  {
    line1: "14/A, Boat Club Road",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411001",
  },
  {
    line1: "Flat 3A, Ocean View, Worli Sea Face",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400030",
  },
  {
    line1: "D-56, Panchsheel Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110017",
  },
  {
    line1: "Plot 10, Sector 18, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "4th Floor, Brigade Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "No. 45, T. Nagar, Usman Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600017",
  },
  {
    line1: "A-701, Raheja Gardens, Wanowrie",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411040",
  },
  {
    line1: "House 12, Civil Lines",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "440001",
  },
  {
    line1: "Sector 4, HSR Layout, 27th Main",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560102",
  },
  {
    line1: "Flat 6B, Park Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700016",
  },
  {
    line1: "Plot 22, Infocity, Patia",
    city: "Bhubaneswar",
    state: "Odisha",
    stateCode: "21",
    pincode: "751024",
  },
  {
    line1: "78, Race Course Road",
    city: "Coimbatore",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "641018",
  },
  {
    line1: "No. 15, Residency Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560025",
  },
  {
    line1: "Block C, Indiranagar, 100 Feet Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560038",
  },
  {
    line1: "A-12, Vaishali Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "302021",
  },
  {
    line1: "Flat 401, Divine Bliss, Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600020",
  },
  {
    line1: "H-9, Palam Vihar",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122017",
  },
  {
    line1: "22/1, Garia Station Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700084",
  },
  {
    line1: "Plot 5, Sector 2, Raj Nagar",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201002",
  },
  {
    line1: "No. 5, Lavelle Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Flat 1204, Lodha Bellissimo, Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400013",
  },
  {
    line1: "67, MP Nagar Zone II",
    city: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "462011",
  },
  {
    line1: "C-45, Ashok Nagar",
    city: "Ranchi",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "834002",
  },
  {
    line1: "House 4, Boring Road",
    city: "Patna",
    state: "Bihar",
    stateCode: "10",
    pincode: "800001",
  },
  {
    line1: "Room 5, Charni Road",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400004",
  },
  {
    line1: "Plot No. 12, IT Park",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160101",
  },
  {
    line1: "No. 89, Jayanagar 4th Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560011",
  },
  {
    line1: "B-10, Model Town",
    city: "Ludhiana",
    state: "Punjab",
    stateCode: "03",
    pincode: "141002",
  },
  {
    line1: "34, Sardar Patel Marg",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110021",
  },
  {
    line1: "Flat 302, Sai Sadan, Matunga",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400019",
  },
  {
    line1: "Plot 15, MIHAN",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "441108",
  },
  {
    line1: "No. 12, Cunningham Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560052",
  },
  {
    line1: "D-2, South Extension II",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110049",
  },
  {
    line1: "67, Anna Nagar West",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600040",
  },
  {
    line1: "Flat 9, Regency Park, DLF Phase IV",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122009",
  },
  {
    line1: "Villa 45, Nandi Hills Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "562103",
  },
  {
    line1: "A-8, Shastri Nagar",
    city: "Jodhpur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "342003",
  },
  {
    line1: "C-101, Blue Heaven, Kandivali East",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400101",
  },
  {
    line1: "No. 4, Richmond Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560025",
  },
  {
    line1: "Flat 202, Palm Beach Road",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400706",
  },
  {
    line1: "House No. 12, Sector 8",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160009",
  },
  {
    line1: "33, Mount Road, Guindy",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600032",
  },
  {
    line1: "Plot 56, Electronic City Phase I",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560100",
  },
  {
    line1: "Flat 8A, Camac Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700017",
  },
  {
    line1: "B-50, Rajouri Garden",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110027",
  },
  {
    line1: "H-202, Seasons Apartment, Aundh",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411007",
  },
  {
    line1: "No. 56, Besant Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600090",
  },
  {
    line1: "Flat 301, Lakeview Enclave, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500032",
  },
  {
    line1: "22, Civil Lines",
    city: "Allahabad",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "211001",
  },
  {
    line1: "No. 10, Brigade Gateway, Rajajinagar",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560055",
  },
  {
    line1: "A-44, Vijay Nagar",
    city: "Indore",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "452010",
  },
  {
    line1: "Plot 101, GIDC Estate",
    city: "Surat",
    state: "Gujarat",
    stateCode: "24",
    pincode: "395007",
  },
  {
    line1: "Flat 12, Marine Drive",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400020",
  },
  {
    line1: "No. 7, Old Airport Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560017",
  },
  {
    line1: "C-12, Arera Colony",
    city: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "462016",
  },
  {
    line1: "Flat 405, Hill Crest, Hebbal",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560024",
  },
  {
    line1: "House 23, Mahanagar",
    city: "Lucknow",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "226006",
  },
  {
    line1: "Plot 8, Sector 125",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201303",
  },
  {
    line1: "No. 19, Kasba",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700042",
  },
  {
    line1: "A-501, Serene County, Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500032",
  },
  {
    line1: "Flat 102, Gokuldham, Goregaon East",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400063",
  },
  {
    line1: "No. 45, Residency Road",
    city: "Jammu",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "180001",
  },
  {
    line1: "C-2, Vasant Vihar",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110057",
  },
  {
    line1: "Flat 3, Shakespeare Sarani",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700071",
  },
  {
    line1: "Plot No. 78, Hadapsar Industrial Estate",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411013",
  },
  {
    line1: "No. 15, Cathedral Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600086",
  },
  {
    line1: "A-302, Palm Springs, Malad West",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400064",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Jaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "302006",
  },
  {
    line1: "Plot 12, Salt Lake, Sector V",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700091",
  },
  {
    line1: "Flat 501, Marvel Ritz, Hadapsar",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411028",
  },
  {
    line1: "No. 8, MG Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "B-4, Janakpuri",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110058",
  },
  {
    line1: "Flat 602, Mantri Elegance, Bannerghatta Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560076",
  },
  {
    line1: "No. 55, Mylapore",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600004",
  },
  {
    line1: "Plot 90, Sector 44",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122003",
  },
  {
    line1: "House 121, Sector 21",
    city: "Faridabad",
    state: "Haryana",
    stateCode: "06",
    pincode: "121001",
  },
  {
    line1: "C-90, Saket",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110017",
  },
  {
    line1: "Flat 10B, Middleton Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700071",
  },
  {
    line1: "No. 6, St. Marks Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Plot 102, Gachibowli Financial District",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500032",
  },
  {
    line1: "House No. 45, Model Town",
    city: "Jalandhar",
    state: "Punjab",
    stateCode: "03",
    pincode: "144003",
  },
  {
    line1: "A-12, Aliganj",
    city: "Lucknow",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "226024",
  },
  {
    line1: "Flat 301, Silver Sands, Versova",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400061",
  },
  {
    line1: "No. 34, West Mambalam",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600033",
  },
  {
    line1: "Plot 5, Sector 5, Dwarka",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110075",
  },
  {
    line1: "Flat 204, Ganga Constella, Kharadi",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411014",
  },
  {
    line1: "No. 12, Richmond Town",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560025",
  },
  {
    line1: "A-7, Tilak Nagar",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110018",
  },
  {
    line1: "Plot 10, Industrial Area Phase I",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160002",
  },
  {
    line1: "Flat 5A, Ballygunge Circular Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700019",
  },
  {
    line1: "No. 45, Nungambakkam High Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600034",
  },
  {
    line1: "B-101, Lodha Aqua, Mira Road",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "401107",
  },
  {
    line1: "House 12, Palam Vihar",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122017",
  },
  {
    line1: "No. 8, Palace Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560052",
  },
  {
    line1: "Flat 302, Sai Sagar, Dadar West",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400028",
  },
  {
    line1: "A-56, Rohini Sector 9",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110085",
  },
  {
    line1: "Plot 22, Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201309",
  },
  {
    line1: "No. 12, Royapettah",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600014",
  },
  {
    line1: "Flat 101, Hill Side, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500033",
  },
  {
    line1: "House No. 34, Civil Lines",
    city: "Bareilly",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "243001",
  },
  {
    line1: "C-4, Defence Colony",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110024",
  },
  {
    line1: "Flat 202, Green Glen Layout, Bellandur",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560103",
  },
  {
    line1: "No. 90, TTK Road, Alwarpet",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600018",
  },
  {
    line1: "Plot 4, Infotech Park, Hinjewadi",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411057",
  },
  {
    line1: "Flat 301, Sea View, Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400050",
  },
  {
    line1: "A-1, Sarvodaya Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110017",
  },
  {
    line1: "No. 15, Frazer Town",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560005",
  },
  {
    line1: "Flat 602, Skyline Apartments, Hebbal",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560024",
  },
  {
    line1: "House 5, Mira Bagh",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110063",
  },
  {
    line1: "Plot 12, Sector 15",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122001",
  },
  {
    line1: "Flat 4B, Wood Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700016",
  },
  {
    line1: "No. 22, Gandhi Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600020",
  },
  {
    line1: "A-301, Blue Ridge, Hinjewadi Phase 1",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411057",
  },
  {
    line1: "House No. 90, Sector 10",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160010",
  },
  {
    line1: "C-12, Green Park Main",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110016",
  },
  {
    line1: "Flat 102, Paramount, HSR Layout",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560102",
  },
  {
    line1: "No. 8, Race Course Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Plot 45, Sector 11, CBD Belapur",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400614",
  },
  {
    line1: "Flat 501, Lake Homes, Powai",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400076",
  },
  {
    line1: "A-15, Greater Kailash I",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110048",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "440001",
  },
  {
    line1: "No. 12, Indiranagar 2nd Stage",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560038",
  },
  {
    line1: "Flat 202, Sunny Side, Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400049",
  },
  {
    line1: "C-9, Vasant Kunj",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110070",
  },
  {
    line1: "Plot 5, Electronic City Phase II",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560100",
  },
  {
    line1: "Flat 4A, Southern Avenue",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700029",
  },
  {
    line1: "No. 45, Kasturba Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "A-202, Whispering Palms, Kandivali",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400101",
  },
  {
    line1: "House No. 12, Sector 2",
    city: "Panchkula",
    state: "Haryana",
    stateCode: "06",
    pincode: "134109",
  },
  {
    line1: "C-1, Gulmohar Park",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110049",
  },
  {
    line1: "Flat 101, Signature Towers, Kondapur",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500084",
  },
  {
    line1: "No. 90, Peters Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600014",
  },
  {
    line1: "Plot 22, Kharadi IT Park",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411014",
  },
  {
    line1: "Flat 302, Sea Face Apartment, Worli",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400030",
  },
  {
    line1: "A-12, Neeti Bagh",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110049",
  },
  {
    line1: "No. 5, Lavelle Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Flat 505, Mantri Altius, Raj Bhavan Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "House 23, Sector 15-A",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "Plot 10, Sector 34",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122004",
  },
  {
    line1: "Flat 6B, Elgin Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700020",
  },
  {
    line1: "No. 22, Kutchery Road, Mylapore",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600004",
  },
  {
    line1: "A-301, Amanora Park Town, Hadapsar",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411028",
  },
  {
    line1: "House No. 90, Sector 11",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160011",
  },
  {
    line1: "C-12, East of Kailash",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110065",
  },
  {
    line1: "Flat 102, Ferns Residency, Hennur",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560043",
  },
  {
    line1: "No. 8, High Street, Cooke Town",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560005",
  },
  {
    line1: "Plot 45, Sector 4, Kalamboli",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "410218",
  },
  {
    line1: "Flat 501, Hiranandani Meadows",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400610",
  },
  {
    line1: "A-15, Anand Niketan",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110021",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Ludhiana",
    state: "Punjab",
    stateCode: "03",
    pincode: "141001",
  },
  {
    line1: "No. 12, Koramangala 3rd Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560034",
  },
  {
    line1: "Flat 202, Silver Arch, Nepean Sea Road",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400006",
  },
  {
    line1: "C-9, Safdarjung Development Area",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110016",
  },
  {
    line1: "Plot 5, Bagmane Tech Park, CV Raman Nagar",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560093",
  },
  {
    line1: "Flat 4A, Sarat Bose Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700020",
  },
  {
    line1: "No. 45, Mount Road, Nandanam",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600035",
  },
  {
    line1: "A-202, Rustomjee Elements, Upper Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400053",
  },
  {
    line1: "House No. 12, Sector 4",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122001",
  },
  {
    line1: "C-1, West End",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110021",
  },
  {
    line1: "Flat 101, Lanco Hills, Manikonda",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500089",
  },
  {
    line1: "No. 90, Luz Church Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600004",
  },
  {
    line1: "Plot 22, Magarpatta City",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411013",
  },
  {
    line1: "Flat 302, BeauMonde, Prabhadevi",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400025",
  },
  {
    line1: "A-12, Shanti Niketan",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110021",
  },
  {
    line1: "No. 5, Ulsoor Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560042",
  },
  {
    line1: "Flat 505, Phoenix One Bangalore West",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560010",
  },
  {
    line1: "House 23, Sector 27",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "Plot 10, Sector 48",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122018",
  },
  {
    line1: "Flat 6B, Loudon Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700017",
  },
  {
    line1: "No. 22, Spurtank Road, Chetpet",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600031",
  },
  {
    line1: "A-301, Blue Gardens, Wakad",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411057",
  },
  {
    line1: "House No. 90, Sector 15",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160015",
  },
  {
    line1: "C-12, Kailash Colony",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110048",
  },
  {
    line1: "Flat 102, Embassy Golf Links, Domlur",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560071",
  },
  {
    line1: "No. 8, Infantry Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Plot 45, Sector 17, Vashi",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400703",
  },
  {
    line1: "Flat 501, Hiranandani Estate",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400607",
  },
  {
    line1: "A-15, New Friends Colony",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110025",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Amritsar",
    state: "Punjab",
    stateCode: "03",
    pincode: "143001",
  },
  {
    line1: "No. 12, Indiranagar 1st Stage",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560038",
  },
  {
    line1: "Flat 202, Silver Sands, Versova",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400061",
  },
  {
    line1: "C-9, Greater Kailash II",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110048",
  },
  {
    line1: "Plot 5, Manyata Tech Park, Hebbal",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560045",
  },
  {
    line1: "Flat 4A, Dover Lane",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700029",
  },
  {
    line1: "No. 45, Sterling Road, Nungambakkam",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600034",
  },
  {
    line1: "A-202, Imperial Heights, Goregaon",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400104",
  },
  {
    line1: "House No. 12, Sector 14",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122001",
  },
  {
    line1: "C-1, Friends Colony West",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110065",
  },
  {
    line1: "Flat 101, My Home Abhra, Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500081",
  },
  {
    line1: "No. 90, Chamiers Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600028",
  },
  {
    line1: "Plot 22, EON Free Zone, Kharadi",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411014",
  },
  {
    line1: "Flat 302, World Crest, Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400013",
  },
  {
    line1: "A-12, Maharani Bagh",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110065",
  },
  {
    line1: "No. 5, Sankey Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560020",
  },
  {
    line1: "Flat 505, Karle Town Centre, Hebbal",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560045",
  },
  {
    line1: "House 23, Sector 39",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "Plot 10, Sector 54",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122003",
  },
  {
    line1: "Flat 6B, Rawdon Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700017",
  },
  {
    line1: "No. 22, Harrington Road, Chetpet",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600031",
  },
  {
    line1: "A-301, Puranik City, Ghodbunder Road",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400615",
  },
  {
    line1: "House No. 90, Sector 16",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160016",
  },
  {
    line1: "C-12, Nizamuddin East",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110013",
  },
  {
    line1: "Flat 102, Sobha Iris, Outer Ring Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560103",
  },
  {
    line1: "No. 8, Commercial Street",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Plot 45, Sector 15, Belapur",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400614",
  },
  {
    line1: "Flat 501, Rustomjee Meridian, Kandivali",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400067",
  },
  {
    line1: "A-15, Gulmohar Park",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110049",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Rohtak",
    state: "Haryana",
    stateCode: "06",
    pincode: "124001",
  },
  {
    line1: "No. 12, Jayanagar 5th Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560041",
  },
  {
    line1: "Flat 202, Kanakia Rainforest, Marol",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400059",
  },
  {
    line1: "C-9, Safdarjung Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110029",
  },
  {
    line1: "Plot 5, RMZ Ecoworld, Bellandur",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560103",
  },
  {
    line1: "Flat 4A, Keyatala Road",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700029",
  },
  {
    line1: "No. 45, Pantheon Road, Egmore",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600008",
  },
  {
    line1: "A-202, Oberoi Splendor, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400060",
  },
  {
    line1: "House No. 12, Sector 23",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122017",
  },
  {
    line1: "C-1, Jangpura Extension",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110014",
  },
  {
    line1: "Flat 101, My Home Bhooja, HITEC City",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500081",
  },
  {
    line1: "No. 90, Greams Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600006",
  },
  {
    line1: "Plot 22, Commerzone, Yerwada",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411006",
  },
  {
    line1: "Flat 302, Omkar 1973, Worli",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400030",
  },
  {
    line1: "A-12, Hemkunt Colony",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110048",
  },
  {
    line1: "No. 5, Race Course Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Flat 505, Brigade Exotica, Old Madras Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560049",
  },
  {
    line1: "House 23, Sector 44",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "Plot 10, Sector 56",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122011",
  },
  {
    line1: "Flat 6B, Little Russell Street",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700071",
  },
  {
    line1: "No. 22, Haddows Road, Nungambakkam",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600006",
  },
  {
    line1: "A-301, Lodha Amara, Kolshet Road",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400607",
  },
  {
    line1: "House No. 90, Sector 17",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160017",
  },
  {
    line1: "C-12, Sarita Vihar",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110076",
  },
  {
    line1: "Flat 102, Mantri Greens, Malleshwaram",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560003",
  },
  {
    line1: "No. 8, Cubbon Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560001",
  },
  {
    line1: "Plot 45, Sector 19, Airoli",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400708",
  },
  {
    line1: "Flat 501, Kalpataru Aura, Ghatkopar",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400086",
  },
  {
    line1: "A-15, Kalkaji",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110019",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Meerut",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "250001",
  },
  {
    line1: "No. 12, Jayanagar 7th Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560070",
  },
  {
    line1: "Flat 202, Acme Ozone, Manpada",
    city: "Thane",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400607",
  },
  {
    line1: "C-9, Malviya Nagar",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110017",
  },
  {
    line1: "Plot 5, Bagmane World Technology Center",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560048",
  },
  {
    line1: "Flat 4A, Southern Avenue",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700029",
  },
  {
    line1: "No. 45, Sardar Patel Road, Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600020",
  },
  {
    line1: "A-202, Godrej Garden City, SG Highway",
    city: "Ahmedabad",
    state: "Gujarat",
    stateCode: "24",
    pincode: "382470",
  },
  {
    line1: "House No. 12, Sector 15",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122001",
  },
  {
    line1: "C-1, Lajpat Nagar IV",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110024",
  },
  {
    line1: "Flat 101, My Home Avatar, Puppalaguda",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "36",
    pincode: "500089",
  },
  {
    line1: "No. 90, TTK Road",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600018",
  },
  {
    line1: "Plot 22, Cerebrum IT Park, Kalyani Nagar",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "411014",
  },
  {
    line1: "Flat 302, Lodha Altamount, Altamount Road",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400026",
  },
  {
    line1: "A-12, Pamposh Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110048",
  },
  {
    line1: "No. 5, Millers Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560046",
  },
  {
    line1: "Flat 505, Prestige Shantiniketan, Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560048",
  },
  {
    line1: "House 23, Sector 50",
    city: "Noida",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "201301",
  },
  {
    line1: "Plot 10, Sector 57",
    city: "Gurugram",
    state: "Haryana",
    stateCode: "06",
    pincode: "122003",
  },
  {
    line1: "Flat 6B, Woodburn Park",
    city: "Kolkata",
    state: "West Bengal",
    stateCode: "19",
    pincode: "700020",
  },
  {
    line1: "No. 22, Ethiraj Salai",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "600008",
  },
  {
    line1: "A-301, Hiranandani Zenith",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "603103",
  },
  {
    line1: "House No. 90, Sector 18",
    city: "Chandigarh",
    state: "Chandigarh",
    stateCode: "04",
    pincode: "160018",
  },
  {
    line1: "C-12, Chittaranjan Park",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110019",
  },
  {
    line1: "Flat 102, Purva Riviera, Marathahalli",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560037",
  },
  {
    line1: "No. 8, Sankey Road",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560020",
  },
  {
    line1: "Plot 45, Sector 20, Nerul",
    city: "Navi Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400706",
  },
  {
    line1: "Flat 501, Rustomjee Elements",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400053",
  },
  {
    line1: "A-15, Safdarjung Enclave",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110029",
  },
  {
    line1: "House No. 1, Civil Lines",
    city: "Bathinda",
    state: "Punjab",
    stateCode: "03",
    pincode: "151001",
  },
  {
    line1: "No. 12, Jayanagar 9th Block",
    city: "Bengaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "560069",
  },
  {
    line1: "Flat 202, Raheja Vistas, Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "400072",
  },
  {
    line1: "C-9, Gulmohar Park",
    city: "New Delhi",
    state: "Delhi",
    stateCode: "07",
    pincode: "110049",
  },
  {
    line1: "Flat 302, Sai Sagar Enclave, Akkayyapalem",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "530016",
  },
  {
    line1: "Plot No. 12, Revenue Colony, Marripalem",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "530018",
  },
  {
    line1: "H.No. 4-55, MVP Colony, Sector 3",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "530017",
  },
  {
    line1: "Door No. 10-2-1, Gandhi Nagar",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "520003",
  },
  {
    line1: "Plot 89, Bharathi Nagar, Near Ring Road",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "520008",
  },
  {
    line1: "Shop 4, Market Road",
    city: "Guntur",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "522001",
  },
  {
    line1: "H.No 12/A, Lakshmipuram 3rd Lane",
    city: "Guntur",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "522007",
  },
  {
    line1: "No. 44, NGO Colony",
    city: "Tirupati",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "517501",
  },
  {
    line1: "Villa 9, Lotus Homes, Karakambadi Road",
    city: "Tirupati",
    state: "Andhra Pradesh",
    stateCode: "37",
    pincode: "517507",
  },
  {
    line1: "House No. 15, Near Zoo Road",
    city: "Guwahati",
    state: "Assam",
    stateCode: "18",
    pincode: "781005",
  },
  {
    line1: "Flat 204, Brahmaputra Apartments, Silpukhuri",
    city: "Guwahati",
    state: "Assam",
    stateCode: "18",
    pincode: "781003",
  },
  {
    line1: "Plot 7, G.S. Road, Christian Basti",
    city: "Guwahati",
    state: "Assam",
    stateCode: "18",
    pincode: "781005",
  },
  {
    line1: "H.No. 122, Boring Road, Near Pantaloons",
    city: "Patna",
    state: "Bihar",
    stateCode: "10",
    pincode: "800001",
  },
  {
    line1: "Flat 102, Maurya Residency, Kankarbagh",
    city: "Patna",
    state: "Bihar",
    stateCode: "10",
    pincode: "800020",
  },
  {
    line1: "House No. 4, Rajendra Nagar",
    city: "Patna",
    state: "Bihar",
    stateCode: "10",
    pincode: "800016",
  },
  {
    line1: "Plot 56, Zero Mile, NH-31",
    city: "Muzaffarpur",
    state: "Bihar",
    stateCode: "10",
    pincode: "842001",
  },
  {
    line1: "Shop No. 12, Station Road",
    city: "Bhagalpur",
    state: "Bihar",
    stateCode: "10",
    pincode: "812001",
  },
  {
    line1: "House No. 88, Civil Lines, Near Sessions Court",
    city: "Raipur",
    state: "Chhattisgarh",
    stateCode: "22",
    pincode: "492001",
  },
  {
    line1: "Flat 405, Sky High Towers, Shankar Nagar",
    city: "Raipur",
    state: "Chhattisgarh",
    stateCode: "22",
    pincode: "492007",
  },
  {
    line1: "Plot No. 15, Tatibandh Industrial Area",
    city: "Raipur",
    state: "Chhattisgarh",
    stateCode: "22",
    pincode: "492099",
  },
  {
    line1: "House No. 4, Nehru Nagar (East)",
    city: "Bhilai",
    state: "Chhattisgarh",
    stateCode: "22",
    pincode: "490020",
  },
  {
    line1: "Sector 6, Street 12, Quarter 14",
    city: "Bhilai",
    state: "Chhattisgarh",
    stateCode: "22",
    pincode: "490006",
  },
  {
    line1: "Plot 23, Vyas Complex, Adajan",
    city: "Surat",
    state: "Gujarat",
    stateCode: "24",
    pincode: "395009",
  },
  {
    line1: "Flat 701, Riverfront View, Piplod",
    city: "Surat",
    state: "Gujarat",
    stateCode: "24",
    pincode: "395007",
  },
  {
    line1: "Shop 15, Ring Road Market",
    city: "Surat",
    state: "Gujarat",
    stateCode: "24",
    pincode: "395002",
  },
  {
    line1: "House 12, Akota Garden",
    city: "Vadodara",
    state: "Gujarat",
    stateCode: "24",
    pincode: "390020",
  },
  {
    line1: "Plot 5, Alkapuri, Near Station Road",
    city: "Vadodara",
    state: "Gujarat",
    stateCode: "24",
    pincode: "390007",
  },
  {
    line1: "Flat 303, Krishna Kunj, Gotri Road",
    city: "Vadodara",
    state: "Gujarat",
    stateCode: "24",
    pincode: "390021",
  },
  {
    line1: "House 45, Race Course Road",
    city: "Rajkot",
    state: "Gujarat",
    stateCode: "24",
    pincode: "360001",
  },
  {
    line1: "Plot 10, Kalavad Road",
    city: "Rajkot",
    state: "Gujarat",
    stateCode: "24",
    pincode: "360005",
  },
  {
    line1: "H.No. 12, Vidyanagar",
    city: "Anand",
    state: "Gujarat",
    stateCode: "24",
    pincode: "388001",
  },
  {
    line1: "Plot 8, Sector 14, Near ITI",
    city: "Hisar",
    state: "Haryana",
    stateCode: "06",
    pincode: "125001",
  },
  {
    line1: "House 455, Model Town Phase I",
    city: "Rohtak",
    state: "Haryana",
    stateCode: "06",
    pincode: "124001",
  },
  {
    line1: "Plot 12, HUDA Sector 13",
    city: "Karnal",
    state: "Haryana",
    stateCode: "06",
    pincode: "132001",
  },
  {
    line1: "Shop 45, Main Market, Panipat",
    city: "Panipat",
    state: "Haryana",
    stateCode: "06",
    pincode: "132103",
  },
  {
    line1: "Villa 15, Strawberry Hills",
    city: "Shimla",
    state: "Himachal Pradesh",
    stateCode: "02",
    pincode: "171002",
  },
  {
    line1: "House No. 4, Mall Road, Near Lift",
    city: "Shimla",
    state: "Himachal Pradesh",
    stateCode: "02",
    pincode: "171001",
  },
  {
    line1: "Plot 7, Sanjauli Market",
    city: "Shimla",
    state: "Himachal Pradesh",
    stateCode: "02",
    pincode: "171006",
  },
  {
    line1: "House 10, Gandhi Chowk",
    city: "Dharamshala",
    state: "Himachal Pradesh",
    stateCode: "02",
    pincode: "176215",
  },
  {
    line1: "Plot 12, Bari Brahmana Industrial Area",
    city: "Samba",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "181133",
  },
  {
    line1: "House No. 45, Channi Himmat",
    city: "Jammu",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "180015",
  },
  {
    line1: "Flat 302, Tawi View, Gandhi Nagar",
    city: "Jammu",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "180004",
  },
  {
    line1: "House 5, Raj Bagh",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "190008",
  },
  {
    line1: "Plot 12, Lal Chowk",
    city: "Srinagar",
    state: "Jammu & Kashmir",
    stateCode: "01",
    pincode: "190001",
  },
  {
    line1: "House No. 12, Ashok Nagar",
    city: "Ranchi",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "834002",
  },
  {
    line1: "Flat 201, Hill View, Bariatu",
    city: "Ranchi",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "834009",
  },
  {
    line1: "Plot 45, Bistupur Main Road",
    city: "Jamshedpur",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "831001",
  },
  {
    line1: "House 10, Sakchi",
    city: "Jamshedpur",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "831001",
  },
  {
    line1: "Quarter No. 445, Sector 4",
    city: "Bokaro Steel City",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "827004",
  },
  {
    line1: "House No. 12, Saraswathipuram",
    city: "Mysuru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "570009",
  },
  {
    line1: "Plot 5, Gokulam 3rd Stage",
    city: "Mysuru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "570002",
  },
  {
    line1: "Flat 404, Chamundi View, JP Nagar",
    city: "Mysuru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "570008",
  },
  {
    line1: "H.No. 45, Vidyanagar",
    city: "Hubballi",
    state: "Karnataka",
    stateCode: "29",
    pincode: "580021",
  },
  {
    line1: "Plot 10, Akshay Colony",
    city: "Hubballi",
    state: "Karnataka",
    stateCode: "29",
    pincode: "580030",
  },
  {
    line1: "House 12, Tilakwadi",
    city: "Belagavi",
    state: "Karnataka",
    stateCode: "29",
    pincode: "590006",
  },
  {
    line1: "Villa 4, Kadri Hills",
    city: "Mangaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "575002",
  },
  {
    line1: "Flat 101, Ocean View, Bejai",
    city: "Mangaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "575004",
  },
  {
    line1: "Plot 12, MG Road",
    city: "Mangaluru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "575001",
  },
  {
    line1: "House 22, Panampilly Nagar",
    city: "Kochi",
    state: "Kerala",
    stateCode: "32",
    pincode: "682036",
  },
  {
    line1: "Flat 5C, Skyline Heritage, Marine Drive",
    city: "Kochi",
    state: "Kerala",
    stateCode: "32",
    pincode: "682031",
  },
  {
    line1: "Plot 10, Edappally",
    city: "Kochi",
    state: "Kerala",
    stateCode: "32",
    pincode: "682024",
  },
  {
    line1: "Villa 15, Kowdiar",
    city: "Thiruvananthapuram",
    state: "Kerala",
    stateCode: "32",
    pincode: "695003",
  },
  {
    line1: "House No. 12, Pattom",
    city: "Thiruvananthapuram",
    state: "Kerala",
    stateCode: "32",
    pincode: "695004",
  },
  {
    line1: "Plot 5, East Hill",
    city: "Kozhikode",
    state: "Kerala",
    stateCode: "32",
    pincode: "673005",
  },
  {
    line1: "House 12, Civil Lines",
    city: "Indore",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "452001",
  },
  {
    line1: "Flat 302, Royal Residency, Vijay Nagar",
    city: "Indore",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "452010",
  },
  {
    line1: "Plot 45, Rau Industrial Area",
    city: "Indore",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "453331",
  },
  {
    line1: "House No. 90, Arera Colony",
    city: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "462016",
  },
  {
    line1: "Flat 101, Lake View, Shyamla Hills",
    city: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "462013",
  },
  {
    line1: "Plot 12, Maharana Pratap Nagar",
    city: "Bhopal",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "462011",
  },
  {
    line1: "House 44, Madhav Nagar",
    city: "Ujjain",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "456010",
  },
  {
    line1: "H.No. 12, City Center",
    city: "Gwalior",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "474011",
  },
  {
    line1: "House No. 8, Wright Town",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    stateCode: "23",
    pincode: "482002",
  },
  {
    line1: "Plot 10, Civil Lines",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "440001",
  },
  {
    line1: "Flat 405, Orange Heights, Dharampeth",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "440010",
  },
  {
    line1: "Plot 56, MIDC Hingna",
    city: "Nagpur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "440028",
  },
  {
    line1: "House No. 12, Cidco Sector N-1",
    city: "Aurangabad",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "431003",
  },
  {
    line1: "Plot 5, Cannaught Place",
    city: "Aurangabad",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "431001",
  },
  {
    line1: "House 45, Sharanpur Road",
    city: "Nashik",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "422002",
  },
  {
    line1: "Flat 202, Grape City Enclave, College Road",
    city: "Nashik",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "422005",
  },
  {
    line1: "Plot 10, Satpur MIDC",
    city: "Nashik",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "422007",
  },
  {
    line1: "House 12, Laxmipuri",
    city: "Kolhapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416002",
  },
  {
    line1: "House No. 4, Civil Lines",
    city: "Amravati",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "444601",
  },
  {
    line1: "Plot 15, Saheed Nagar",
    city: "Bhubaneswar",
    state: "Odisha",
    stateCode: "21",
    pincode: "751007",
  },
  {
    line1: "Flat 301, Lingaraj View, Nayapalli",
    city: "Bhubaneswar",
    state: "Odisha",
    stateCode: "21",
    pincode: "751012",
  },
  {
    line1: "House No. 10, Chandrasekharpur",
    city: "Bhubaneswar",
    state: "Odisha",
    stateCode: "21",
    pincode: "751016",
  },
  {
    line1: "Plot 4, Cantonment Road",
    city: "Cuttack",
    state: "Odisha",
    stateCode: "21",
    pincode: "753001",
  },
  {
    line1: "House 12, Civil Township",
    city: "Rourkela",
    state: "Odisha",
    stateCode: "21",
    pincode: "769004",
  },
  {
    line1: "Shop 5, Big Bazaar Street",
    city: "Coimbatore",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "641001",
  },
  {
    line1: "Flat 102, Nilgiri View, RS Puram",
    city: "Coimbatore",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "641002",
  },
  {
    line1: "Plot 45, Avinashi Road",
    city: "Coimbatore",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "641018",
  },
  {
    line1: "House No. 12, Anna Nagar",
    city: "Madurai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "625020",
  },
  {
    line1: "Plot 5, KK Nagar",
    city: "Madurai",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "625020",
  },
  {
    line1: "House 15, Thillai Nagar",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "620018",
  },
  {
    line1: "Plot 10, Cantonment",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "620001",
  },
  {
    line1: "House No. 4, Fairlands",
    city: "Salem",
    state: "Tamil Nadu",
    stateCode: "33",
    pincode: "636016",
  },
  {
    line1: "H.No. 4-12, Hanamkonda",
    city: "Warangal",
    state: "Telangana",
    stateCode: "36",
    pincode: "506001",
  },
  {
    line1: "Plot 5, Subedari",
    city: "Warangal",
    state: "Telangana",
    stateCode: "36",
    pincode: "506001",
  },
  {
    line1: "House 10, Ramnagar",
    city: "Karimnagar",
    state: "Telangana",
    stateCode: "36",
    pincode: "505001",
  },
  {
    line1: "House No. 12, Civil Lines",
    city: "Agra",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "282002",
  },
  {
    line1: "Flat 301, Taj View, Fatehabad Road",
    city: "Agra",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "282001",
  },
  {
    line1: "Plot 45, Sanjay Place",
    city: "Agra",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "282002",
  },
  {
    line1: "House No. 90, Sigra",
    city: "Varanasi",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "221010",
  },
  {
    line1: "Flat 101, Ganga View, Lanka",
    city: "Varanasi",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "221005",
  },
  {
    line1: "Plot 12, Cantonment",
    city: "Varanasi",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "221002",
  },
  {
    line1: "House 44, Civil Lines",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "211001",
  },
  {
    line1: "H.No. 12, Ashok Nagar",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "211001",
  },
  {
    line1: "House No. 8, Swaroop Nagar",
    city: "Kanpur",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "208002",
  },
  {
    line1: "Plot 10, Civil Lines",
    city: "Kanpur",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "208001",
  },
  {
    line1: "House No. 12, Shastri Nagar",
    city: "Meerut",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "250004",
  },
  {
    line1: "Plot 5, Civil Lines",
    city: "Bareilly",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "243001",
  },
  {
    line1: "House 45, Gandhi Nagar",
    city: "Moradabad",
    state: "Uttar Pradesh",
    stateCode: "09",
    pincode: "244001",
  },
  {
    line1: "House No. 12, Dehradun Road",
    city: "Roorkee",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "247667",
  },
  {
    line1: "Plot 5, IIT Campus Road",
    city: "Roorkee",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "247667",
  },
  {
    line1: "House 10, Haldwani Road",
    city: "Rudrapur",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "263153",
  },
  {
    line1: "House No. 15, Rajpur Road",
    city: "Dehradun",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "248001",
  },
  {
    line1: "Flat 204, Doon View, Jakhan",
    city: "Dehradun",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "248001",
  },
  {
    line1: "Plot 12, Haridwar Road",
    city: "Dehradun",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "248001",
  },
  {
    line1: "House 5, Kankhal",
    city: "Haridwar",
    state: "Uttarakhand",
    stateCode: "05",
    pincode: "249408",
  },
  {
    line1: "House No. 12, City Center",
    city: "Durgapur",
    state: "West Bengal",
    stateCode: "19",
    pincode: "713216",
  },
  {
    line1: "Plot 5, Bidhan Nagar",
    city: "Durgapur",
    state: "West Bengal",
    stateCode: "19",
    pincode: "713212",
  },
  {
    line1: "House 10, GT Road",
    city: "Asansol",
    state: "West Bengal",
    stateCode: "19",
    pincode: "713301",
  },
  {
    line1: "House No. 15, Hakimpara",
    city: "Siliguri",
    state: "West Bengal",
    stateCode: "19",
    pincode: "734001",
  },
  {
    line1: "Plot 12, Sevoke Road",
    city: "Siliguri",
    state: "West Bengal",
    stateCode: "19",
    pincode: "734001",
  },
  {
    line1: "Flat 202, Hill Top, Near Mall Road",
    city: "Darjeeling",
    state: "West Bengal",
    stateCode: "19",
    pincode: "734101",
  },
  {
    line1: "Plot No. 4, G.T. Road",
    city: "Burdwan",
    state: "West Bengal",
    stateCode: "19",
    pincode: "713101",
  },
  {
    line1: "H.No 45, Model Town Phase III",
    city: "Bathinda",
    state: "Punjab",
    stateCode: "03",
    pincode: "151001",
  },
  {
    line1: "Plot 12, Bibi Wala Road",
    city: "Bathinda",
    state: "Punjab",
    stateCode: "03",
    pincode: "151001",
  },
  {
    line1: "House No. 8, Ranjit Avenue",
    city: "Amritsar",
    state: "Punjab",
    stateCode: "03",
    pincode: "143001",
  },
  {
    line1: "Shop 15, Hall Bazaar",
    city: "Amritsar",
    state: "Punjab",
    stateCode: "03",
    pincode: "143006",
  },
  {
    line1: "House 45, Urban Estate Phase I",
    city: "Patiala",
    state: "Punjab",
    stateCode: "03",
    pincode: "147002",
  },
  {
    line1: "Plot 10, Civil Lines",
    city: "Patiala",
    state: "Punjab",
    stateCode: "03",
    pincode: "147001",
  },
  {
    line1: "House No. 12, Model Town",
    city: "Jalandhar",
    state: "Punjab",
    stateCode: "03",
    pincode: "144003",
  },
  {
    line1: "Plot 5, BSF Chowk",
    city: "Jalandhar",
    state: "Punjab",
    stateCode: "03",
    pincode: "144001",
  },
  {
    line1: "House No. 12, Shastri Nagar",
    city: "Ajmer",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "305001",
  },
  {
    line1: "Plot 5, Civil Lines",
    city: "Ajmer",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "305001",
  },
  {
    line1: "House 10, Bhupalpura",
    city: "Udaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "313001",
  },
  {
    line1: "Flat 302, Lake View, Fatehsagar Road",
    city: "Udaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "313001",
  },
  {
    line1: "Plot 12, Hiran Magri Sector 4",
    city: "Udaipur",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "313002",
  },
  {
    line1: "House No. 4, Shastri Nagar",
    city: "Bikaner",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "334001",
  },
  {
    line1: "Plot 5, JNV Colony",
    city: "Bikaner",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "334001",
  },
  {
    line1: "House 15, Talwandi",
    city: "Kota",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "324005",
  },
  {
    line1: "Plot 10, Vigyan Nagar",
    city: "Kota",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "324005",
  },
  {
    line1: "House No. 12, Sector 7",
    city: "Hanumangarh",
    state: "Rajasthan",
    stateCode: "08",
    pincode: "335513",
  },
  {
    line1: "Flat 101, Temple View, Bodhgaya Road",
    city: "Gaya",
    state: "Bihar",
    stateCode: "10",
    pincode: "823001",
  },
  {
    line1: "Plot 12, Civil Lines",
    city: "Sasaram",
    state: "Bihar",
    stateCode: "10",
    pincode: "821115",
  },
  {
    line1: "House No. 4, Station Road",
    city: "Begusarai",
    state: "Bihar",
    stateCode: "10",
    pincode: "851101",
  },
  {
    line1: "Plot 5, Industrial Area",
    city: "Hajipur",
    state: "Bihar",
    stateCode: "10",
    pincode: "844101",
  },
  {
    line1: "House 10, Main Market",
    city: "Dhanbad",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "826001",
  },
  {
    line1: "Plot 12, Bank More",
    city: "Dhanbad",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "826001",
  },
  {
    line1: "House No. 15, Hirapur",
    city: "Dhanbad",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "826001",
  },
  {
    line1: "House 4, Court Road",
    city: "Deoghar",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "814112",
  },
  {
    line1: "Plot 5, Satsang Nagar",
    city: "Deoghar",
    state: "Jharkhand",
    stateCode: "20",
    pincode: "814112",
  },
  {
    line1: "House No. 12, Gandhi Nagar",
    city: "Berhampur",
    state: "Odisha",
    stateCode: "21",
    pincode: "760001",
  },
  {
    line1: "Plot 5, Main Road",
    city: "Sambalpur",
    state: "Odisha",
    stateCode: "21",
    pincode: "768001",
  },
  {
    line1: "House 10, Burla",
    city: "Sambalpur",
    state: "Odisha",
    stateCode: "21",
    pincode: "768017",
  },
  {
    line1: "Plot 12, Industrial Estate",
    city: "Jharsuguda",
    state: "Odisha",
    stateCode: "21",
    pincode: "768201",
  },
  {
    line1: "House No. 4, Stadium Road",
    city: "Angul",
    state: "Odisha",
    stateCode: "21",
    pincode: "759122",
  },
  {
    line1: "House 12, MG Road",
    city: "Tumakuru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "572101",
  },
  {
    line1: "Plot 5, Siddaganga Layout",
    city: "Tumakuru",
    state: "Karnataka",
    stateCode: "29",
    pincode: "572103",
  },
  {
    line1: "House No. 15, Kuvempu Nagar",
    city: "Shivamogga",
    state: "Karnataka",
    stateCode: "29",
    pincode: "577201",
  },
  {
    line1: "Plot 12, Gandhi Bazaar",
    city: "Shivamogga",
    state: "Karnataka",
    stateCode: "29",
    pincode: "577201",
  },
  {
    line1: "House 10, Vidyanagar",
    city: "Davangere",
    state: "Karnataka",
    stateCode: "29",
    pincode: "577004",
  },
  {
    line1: "Plot 5, MCC B Block",
    city: "Davangere",
    state: "Karnataka",
    stateCode: "29",
    pincode: "577004",
  },
  {
    line1: "House No. 12, Cantonment",
    city: "Ballari",
    state: "Karnataka",
    stateCode: "29",
    pincode: "583104",
  },
  {
    line1: "Plot 10, Gandhinagar",
    city: "Ballari",
    state: "Karnataka",
    stateCode: "29",
    pincode: "583103",
  },
  {
    line1: "House 15, Tilak Nagar",
    city: "Hosapete",
    state: "Karnataka",
    stateCode: "29",
    pincode: "583201",
  },
  {
    line1: "Plot 5, Main Road",
    city: "Hassan",
    state: "Karnataka",
    stateCode: "29",
    pincode: "573201",
  },
  {
    line1: "House No. 12, Civil Lines",
    city: "Solapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "413003",
  },
  {
    line1: "Plot 5, Railway Lines",
    city: "Solapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "413001",
  },
  {
    line1: "House 10, Navi Peth",
    city: "Solapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "413007",
  },
  {
    line1: "House No. 15, Tarabai Park",
    city: "Kolhapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416003",
  },
  {
    line1: "Plot 12, Shahupuri",
    city: "Kolhapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416001",
  },
  {
    line1: "House 5, Rajarampuri",
    city: "Kolhapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416008",
  },
  {
    line1: "House No. 12, Vishrambag",
    city: "Sangli",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416415",
  },
  {
    line1: "Plot 5, Gaonbhag",
    city: "Sangli",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "416416",
  },
  {
    line1: "House 10, Market Yard",
    city: "Karad",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "415110",
  },
  {
    line1: "Plot 12, MIDC",
    city: "Satara",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "415004",
  },
  {
    line1: "House No. 12, MG Road",
    city: "Ratnagiri",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "415612",
  },
  {
    line1: "Plot 5, Civil Lines",
    city: "Chandrapur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "442401",
  },
  {
    line1: "House 10, Gandhi Chowk",
    city: "Latur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "413512",
  },
  {
    line1: "Plot 12, MIDC",
    city: "Latur",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "413531",
  },
  {
    line1: "House No. 4, Station Road",
    city: "Jalgaon",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "425001",
  },
  {
    line1: "Plot 5, MIDC",
    city: "Jalgaon",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "425003",
  },
  {
    line1: "House 10, Adarsh Nagar",
    city: "Akola",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "444001",
  },
  {
    line1: "Plot 12, Civil Lines",
    city: "Akola",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "444001",
  },
  {
    line1: "House No. 12, Civil Lines",
    city: "Dhule",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "424001",
  },
  {
    line1: "Plot 5, Deopur",
    city: "Dhule",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "424002",
  },
  {
    line1: "House 10, Station Road",
    city: "Ahmednagar",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "414001",
  },
  {
    line1: "Plot 12, Savedi",
    city: "Ahmednagar",
    state: "Maharashtra",
    stateCode: "27",
    pincode: "414003",
  },
  {
    line1: "House No. 12, Model Town",
    city: "Rewari",
    state: "Haryana",
    stateCode: "06",
    pincode: "123401",
  },
  {
    line1: "Plot 5, Brass Market",
    city: "Rewari",
    state: "Haryana",
    stateCode: "06",
    pincode: "123401",
  },
  {
    line1: "House 10, Civil Lines",
    city: "Sirsa",
    state: "Haryana",
    stateCode: "06",
    pincode: "125055",
  },
  {
    line1: "Plot 12, HUDA Sector",
    city: "Sirsa",
    state: "Haryana",
    stateCode: "06",
    pincode: "125055",
  },
  {
    line1: "House No. 15, Sector 13",
    city: "Bhiwani",
    state: "Haryana",
    stateCode: "06",
    pincode: "127021",
  },
  {
    line1: "Plot 5, Meham Road",
    city: "Bhiwani",
    state: "Haryana",
    stateCode: "06",
    pincode: "127021",
  },
  {
    line1: "House 10, Railway Road",
    city: "Kurukshetra",
    state: "Haryana",
    stateCode: "06",
    pincode: "136118",
  },
  {
    line1: "Plot 12, Sector 3",
    city: "Kurukshetra",
    state: "Haryana",
    stateCode: "06",
    pincode: "136118",
  },
  {
    line1: "House No. 12, Civil Lines",
    city: "Ambala City",
    state: "Haryana",
    stateCode: "06",
    pincode: "134003",
  },
  {
    line1: "Plot 5, Model Town",
    city: "Ambala City",
    state: "Haryana",
    stateCode: "06",
    pincode: "134003",
  },
  {
    line1: "House 10, Cantt Area",
    city: "Ambala Cantt",
    state: "Haryana",
    stateCode: "06",
    pincode: "133001",
  },
  {
    line1: "Plot 12, Sadar Bazaar",
    city: "Ambala Cantt",
    state: "Haryana",
    stateCode: "06",
    pincode: "133001",
  },
  {
    line1: "House No. 12, HUDA Sector",
    city: "Yamuna Nagar",
    state: "Haryana",
    stateCode: "06",
    pincode: "135001",
  },
  {
    line1: "Plot 5, Model Town",
    city: "Yamuna Nagar",
    state: "Haryana",
    stateCode: "06",
    pincode: "135001",
  },
  {
    line1: "House 10, Civil Lines",
    city: "Kaithal",
    state: "Haryana",
    stateCode: "06",
    pincode: "136027",
  },
  {
    line1: "Plot 12, Ambala Road",
    city: "Kaithal",
    state: "Haryana",
    stateCode: "06",
    pincode: "136027",
  },
  // 👉 Continue this same structure
  // You can safely scale to 100+ by duplicating pattern
];

function simpleSeedHash(input) {
  let hash = 2166136261;

  for (const char of String(input || "mock-address")) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }

  return hash >>> 0;
}

export function buildRealisticIndianPhone(seedInput = "") {
  const prefixes = ["9", "8", "7", "6"];
  let state = simpleSeedHash(seedInput || "mock-india-contact");
  const prefix = prefixes[state % prefixes.length];

  let tail = "";
  for (let i = 0; i < 9; i += 1) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    tail += String(state % 10);
  }

  if (/^(\d)\1{8}$/.test(tail)) {
    tail = `73${tail.slice(2)}`;
  }

  return prefix + tail;
}

export function getRandomMockAddress(seedInput = "") {
  const address =
    MOCK_ADDRESSES[Math.floor(Math.random() * MOCK_ADDRESSES.length)];

  return {
    address: `${address.line1}, ${address.city} ${address.pincode}, ${address.state}, India`,
    stateCode: address.stateCode,
    phone: buildRealisticIndianPhone(
      `${seedInput}-${address.line1}-${address.city}-${address.pincode}`,
    ),
  };
}
