export const categories = [
  {
    id: "shop",
    name: "Shop",
    slug: "shop",
    isSpecialCategory: false,
    badge: "",
  },
  {
    id: "men",
    name: "Men",
    slug: "men",
    isSpecialCategory: false,
    badge: "",
  },
  {
    id: "women",
    name: "Women",
    slug: "women",
    isSpecialCategory: false,
    badge: "",
  },
  {
    id: "kids",
    name: "Kids",
    slug: "kids",
    isSpecialCategory: false,
    badge: "",
  },
  {
    id: "accessories",
    name: "Accessories",
    slug: "accessories",
    isSpecialCategory: false,
    badge: "",
  },
];

export const subcategories = [
  {
    id: "tshirts-men",
    name: "T-Shirts",
    slug: "tshirts-men",
    categoryId: "men",
  },
  {
    id: "shirts-men",
    name: "Shirts",
    slug: "shirts-men",
    categoryId: "men",
  },
  {
    id: "denims-men",
    name: "Denims",
    slug: "denims-men",
    categoryId: "men",
  },
  {
    id: "shorts-men",
    name: "Shorts",
    slug: "shorts-men",
    categoryId: "men",
  },
  {
    id: "footwear-men",
    name: "Footwear",
    slug: "footwear-men",
    categoryId: "men",
  },
  {
    id: "socks-men",
    name: "Socks",
    slug: "socks-men",
    categoryId: "men",
  },
  {
    id: "beach-men",
    name: "Beach Wears",
    slug: "beach-men",
    categoryId: "men",
  },
  {
    id: "jackets-men",
    name: "Jackets",
    slug: "jackets-men",
    categoryId: "men",
  },
  {
    id: "tshirts-women",
    name: "T-Shirts",
    slug: "tshirts-women",
    categoryId: "women",
  },
  {
    id: "shirts-women",
    name: "Shirts",
    slug: "shirts-women",
    categoryId: "women",
  },
  {
    id: "denims-women",
    name: "Denims",
    slug: "denims-women",
    categoryId: "women",
  },
  {
    id: "shorts-women",
    name: "Shorts",
    slug: "shorts-women",
    categoryId: "women",
  },
  {
    id: "fulldresses-women",
    name: "Full Dresses",
    slug: "fulldresses-women",
    categoryId: "women",
  },
  {
    id: "footwear-women",
    name: "Footwear",
    slug: "footwear-women",
    categoryId: "women",
  },
  {
    id: "socks-women",
    name: "Socks",
    slug: "socks-women",
    categoryId: "women",
  },
  {
    id: "jackets-women",
    name: "Jackets",
    slug: "jackets-women",
    categoryId: "women",
  },
  {
    id: "tshirts-kids",
    name: "T-Shirts",
    slug: "tshirts-kids",
    categoryId: "kids",
  },
  {
    id: "shirts-kids",
    name: "Shirts",
    slug: "shirts-kids",
    categoryId: "kids",
  },
  {
    id: "shorts-kids",
    name: "Shorts",
    slug: "shorts-kids",
    categoryId: "kids",
  },
  {
    id: "cord-kids",
    name: "Co-Ord Set",
    slug: "cord-kids",
    categoryId: "kids",
  },
  {
    id: "jumpsuit-kids",
    name: "Jumpsuits",
    slug: "jumpsuit-kids",
    categoryId: "kids",
  },
  {
    id: "belts-accessories",
    name: "Belts",
    slug: "belts-accessories",
    categoryId: "accessories",
  },
  {
    id: "watch-accessories",
    name: "Watches",
    slug: "watch-accessories",
    categoryId: "accessories",
  },
  {
    id: "wallet-accessories",
    name: "Wallets",
    slug: "wallet-accessories",
    categoryId: "accessories",
  },
  {
    id: "jewellery-accessories",
    name: "Jewellery",
    slug: "jewellery-accessories",
    categoryId: "accessories",
  },
];
